In [5]:
import pandas as pd
# Note values in chart are rounded.
# Note that only a limited number of crash victims in NWT and YK were tested for alcohol and/or drugs, therefore their presence has been assumed to be the same as those among drivers of highway vehicles in the rest of Canada dying within 30 days of the crash

In [6]:
raw_data = {'Location': ['CAN', 'AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'ON', 'PE', 'QC', 'SK', 'NT', 'NU', 'YK'], 
        'Total # of Crash Deaths': [2297, 414, 427, 79, 61, 40, 62, 678, 6, 381, 139, 5, 0, 5], 
        '# of Fatalities Involving Drugs Alone or Drugs and Alcohol': [974, 182, 181, 40, 41, 17, 23, 296, 2, 133, 51, 2, 0, 2], 
        '% of Fatalities Involving Drugs Alone or Drugs and Alcohol': [42.4, 44.0, 42.4, 50.0, 68.0, 42.9, 36.7, 43.6, 33.3, 34.9, 36.8, 42.4, 0.0, 42.4]}
df = pd.DataFrame(raw_data, columns = ['Location', 'Total # of Crash Deaths', '# of Fatalities Involving Drugs Alone or Drugs and Alcohol', '% of Fatalities Involving Drugs Alone or Drugs and Alcohol'])
df

,Location,Total # of Crash Deaths,# of Fatalities Involving Drugs Alone or Drugs and Alcohol,% of Fatalities Involving Drugs Alone or Drugs and Alcohol
0,CAN,2297,974,42.4
1,AB,414,182,44.0
2,BC,427,181,42.4
3,MB,79,40,50.0
4,NB,61,41,68.0
5,NL,40,17,42.9
6,NS,62,23,36.7
7,ON,678,296,43.6
8,PE,6,2,33.3
9,QC,381,133,34.9
10,SK,139,51,36.8
11,NT,5,2,42.4
12,NU,0,0,0.0
13,YK,5,2,42.4

In [7]:
df.to_csv('affectsofsubabuse.csv')